export default {
    input: 'lib/index.js',
    output: {
        file: 'lib/index.cjs',
        format: 'cjs',
        banner: `/*!
 * ⚠️ WARNING: AUTO-GENERATED FILE ⚠️
 * @license
 * 
 * This file is automatically generated by the build process.
 * DO NOT EDIT THIS FILE MANUALLY.
 * 
 * Source: lib/index.js
 * 
 * To update this file, modify the source files in 'lib/src/' or 'lib/index.js'
 * and run 'npm run build'.
 */`
    },
    external: [
        'elliptic',
        'node-fetch',
        'sha256',
        'crypto'
    ]
};
