/*!
 * ⚠️ WARNING: AUTO-GENERATED FILE ⚠️
 * @license
 * 
 * This file is automatically generated by the build process.
 * DO NOT EDIT THIS FILE MANUALLY.
 * 
 * Source: lib/index.js
 * 
 * To update this file, modify the source files in 'lib/src/' or 'lib/index.js'
 * and run 'npm run build'.
 */
'use strict';

var elliptic = require('elliptic');
var sha256 = require('sha256');
var fetch = require('node-fetch');

/**
 * LLMs.txt/AGENTS.md Metadata:
 * Circular Protocol - Standard APIs SDK
 * This file, 'Utils.js', is part of the Circular Protocol JavaScript SDK
 * for Standard API/Blockchain interaction with the Circular Layer 1 Blockchain.
 * 
 * Module: Utils
 * Purpose: Provides utility functions for string manipulation, hex encoding,
 *          timestamp formatting, and error handling used across the SDK.
 * 
 * Circular Protocol SDK - https://circular-protocol.gitbook.io/standard-apis
 * Circular Global Ledgers, Inc. - USA
 * ============================================================================
 */

/**
 * Utility functions for the Circular Protocol SDK.
 * These are pure helper functions with no external state dependencies.
 */
class Utils {
    /**
     * Add a leading zero to numbers less than 10.
     * @param {number} num - Number to pad.
     * @returns {string} Padded number.
     */
    padNumber(num) {
        return num < 10 ? '0' + num : String(num);
    }

    /**
     * Generate a formatted timestamp: YYYY:MM:DD-hh:mm:ss (UTC).
     * @returns {string} Formatted timestamp.
     */
    getFormattedTimestamp() {
        const date = new Date();
        const year = date.getUTCFullYear();
        const month = this.padNumber(date.getUTCMonth() + 1);
        const day = this.padNumber(date.getUTCDate());
        const hours = this.padNumber(date.getUTCHours());
        const minutes = this.padNumber(date.getUTCMinutes());
        const seconds = this.padNumber(date.getUTCSeconds());

        return `${year}:${month}:${day}-${hours}:${minutes}:${seconds}`;
    }

    /**
     * Remove '0x' prefix from hexadecimal strings.
     * @param {string} word - Hex string potentially with '0x' prefix.
     * @returns {string} Hex string without '0x' prefix.
     */
    hexFix(word) {
        if (typeof word === 'string') {
            let Word = word;
            if (word.startsWith('0x')) {
                Word = Word.slice(2);
            }
            return Word;
        }
        return '';
    }

    /**
     * Convert a string to its hexadecimal representation (without '0x').
     * @param {string} str - String to convert.
     * @returns {string} Hexadecimal representation.
     */
    stringToHex(str) {
        let hexString = '';
        for (let i = 0; i < str.length; i++) {
            const hex = str.charCodeAt(i).toString(16);
            hexString += ('00' + hex).slice(-2);
        }
        return hexString;
    }

    /**
     * Convert a hexadecimal string to a regular string.
     * @param {string} hex - Hexadecimal string to convert.
     * @returns {string} Decoded string.
     */
    hexToString(hex) {
        let str = '';
        hex = this.hexFix(hex);
        for (let i = 0; i < hex.length; i += 2) {
            const code = parseInt(hex.substr(i, 2), 16);
            if (!isNaN(code) && code !== 0) {
                str += String.fromCharCode(code);
            }
        }
        return str;
    }

    /**
     * Handle errors with consistent formatting.
     * @param {Error} error - The error to handle.
     * @returns {Object} Error response object.
     */
    handleError(error) {
        console.error('Error:', error);
        const message = error.message || 'An unknown error occurred';
        return { success: false, error: message };
    }
}

/**
 * LLMs.txt/AGENTS.md Metadata:
 * Circular Protocol - Standard APIs SDK
 * This file, 'CryptoService.js', is part of the Circular Protocol JavaScript SDK
 * for Standard API/Blockchain interaction with the Circular Layer 1 Blockchain.
 * 
 * Module: CryptoService
 * Purpose: Provides cryptographic operations including key generation, message
 *          signing, and signature verification using secp256k1 elliptic curves.
 * 
 * Circular Protocol SDK - https://circular-protocol.gitbook.io/standard-apis
 * Circular Global Ledgers, Inc. - USA
 * ============================================================================
 */


/**
 * Cryptographic service for the Circular Protocol SDK.
 * Handles key generation, signing, and verification operations.
 */
class CryptoService {
    /**
     * Create a CryptoService instance.
     * @param {Utils} utils - Utils instance for hex manipulation.
     */
    constructor(utils) {
        this.utils = utils;
        this.EC = elliptic.ec;
        this.ec = new this.EC('secp256k1');
    }

    /**
     * Hash a string using SHA256.
     * @param {string} str - String to hash.
     * @returns {string} SHA256 hash.
     */
    hashString(str) {
        return sha256(str);
    }

    /**
     * Sign a message using secp256k1.
     * @param {string} message - Message to sign.
     * @param {string} privateKey - Private key in hex format (with or without '0x').
     * @returns {string} DER-encoded signature in hex format.
     */
    signMessage(message, privateKey) {
        const key = this.ec.keyFromPrivate(this.utils.hexFix(privateKey), 'hex');
        const msgHash = sha256(message);
        const signature = key.sign(msgHash).toDER('hex');
        return signature;
    }

    /**
     * Verify a message signature.
     * @param {string} publicKey - Public key in hex format.
     * @param {string} message - Original message.
     * @param {string} signature - Signature to verify.
     * @returns {boolean} True if signature is valid.
     */
    verifySignature(publicKey, message, signature) {
        const key = this.ec.keyFromPublic(publicKey, 'hex');
        const msgHash = sha256(message);
        return key.verify(msgHash, signature, 'hex');
    }

    /**
     * Derive a public key from a private key.
     * @param {string} privateKey - Private key in hex format.
     * @returns {string} Public key in hex format.
     */
    getPublicKey(privateKey) {
        const key = this.ec.keyFromPrivate(privateKey, 'hex');
        return key.getPublic('hex');
    }
}

/**
 * LLMs.txt/AGENTS.md Metadata:
 * Circular Protocol - Standard APIs SDK
 * This file, 'WalletAPI.js', is part of the Circular Protocol JavaScript SDK
 * for Standard API/Blockchain interaction with the Circular Layer 1 Blockchain.
 * 
 * Module: WalletAPI
 * Purpose: Provides wallet-related operations including wallet status checks,
 *          balance queries, nonce retrieval, and wallet registration.
 * 
 * Circular Protocol SDK - https://circular-protocol.gitbook.io/standard-apis
 * Circular Global Ledgers, Inc. - USA
 * ============================================================================
 */


/**
 * Wallet operations for the Circular Protocol SDK.
 */
class WalletAPI {
    /**
     * Create a WalletAPI instance.
     * @param {Function} getNAGURL - Function to get current NAG URL.
     * @param {string} version - SDK version string.
     * @param {Utils} utils - Utils instance.
     * @param {Function} sendTransactionFn - Function to send transactions (for registerWallet).
     */
    constructor(getNAGURL, version, utils, sendTransactionFn) {
        this.getNAGURL = getNAGURL;
        this.version = version;
        this.utils = utils;
        this.sendTransaction = sendTransactionFn;
    }

    /**
     * Check if a wallet is registered on the chain.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} address - Wallet address.
     * @returns {Promise<Object>} Wallet status.
     */
    async checkWallet(blockchain, address) {
        const data = {
            "Blockchain": this.utils.hexFix(blockchain),
            "Address": this.utils.hexFix(address),
            "Version": this.version
        };

        try {
            const response = await fetch(this.getNAGURL() + 'Circular_CheckWallet_', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data)
            });

            if (!response.ok) {
                throw new Error('Network response was not ok');
            }

            return await response.json();
        } catch (error) {
            console.error('Error:', error);
            return this.utils.handleError(error);
        }
    }

    /**
     * Retrieve a wallet's information.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} address - Wallet address.
     * @returns {Promise<Object>} Wallet information.
     */
    async getWallet(blockchain, address) {
        const data = {
            "Blockchain": this.utils.hexFix(blockchain),
            "Address": this.utils.hexFix(address),
            "Version": this.version
        };

        try {
            const response = await fetch(this.getNAGURL() + 'Circular_GetWallet_', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data)
            });

            if (!response.ok) {
                throw new Error('Network response was not ok');
            }

            return await response.json();
        } catch (error) {
            console.error('Error:', error);
            return null;
        }
    }

    /**
     * Get the latest transactions for a wallet.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} address - Wallet address.
     * @returns {Promise<Object>} Latest transactions.
     */
    async getLatestTransactions(blockchain, address) {
        const data = {
            "Blockchain": this.utils.hexFix(blockchain),
            "Address": this.utils.hexFix(address),
            "Version": this.version
        };

        try {
            const response = await fetch(this.getNAGURL() + 'Circular_GetLatestTransactions_', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data)
            });

            if (!response.ok) {
                throw new Error('Network response was not ok');
            }

            return await response.json();
        } catch (error) {
            console.error('Error:', error);
            return null;
        }
    }

    /**
     * Get the balance of a specified asset in a wallet.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} address - Wallet address.
     * @param {string} asset - Asset name (e.g., 'CIRX').
     * @returns {Promise<Object>} Wallet balance.
     */
    async getWalletBalance(blockchain, address, asset) {
        const data = {
            "Blockchain": this.utils.hexFix(blockchain),
            "Address": this.utils.hexFix(address),
            "Asset": asset,
            "Version": this.version
        };

        try {
            const response = await fetch(this.getNAGURL() + 'Circular_GetWalletBalance_', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data)
            });

            if (!response.ok) {
                throw new Error('Network response was not ok');
            }

            return await response.json();
        } catch (error) {
            console.error('Error:', error);
            return null;
        }
    }

    /**
     * Get the nonce for a wallet.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} address - Wallet address.
     * @returns {Promise<Object>} Wallet nonce.
     */
    async getWalletNonce(blockchain, address) {
        const data = {
            "Blockchain": this.utils.hexFix(blockchain),
            "Address": this.utils.hexFix(address),
            "Version": this.version
        };

        try {
            const response = await fetch(this.getNAGURL() + 'Circular_GetWalletNonce_', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data)
            });

            if (!response.ok) {
                throw new Error('Network response was not ok');
            }

            return await response.json();
        } catch (error) {
            console.error('Error:', error);
            return null;
        }
    }

    /**
     * Register a wallet on a blockchain.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} publicKey - Wallet public key.
     * @returns {Promise<string>} Transaction ID.
     */
    async registerWallet(blockchain, publicKey) {
        blockchain = this.utils.hexFix(blockchain);
        publicKey = this.utils.hexFix(publicKey);

        const From = sha256(publicKey);
        const To = From;
        const Nonce = '0';
        const Type = 'C_TYPE_REGISTERWALLET';

        const PayloadObj = { "Action": "CP_REGISTERWALLET", "PublicKey": publicKey };
        const jsonstr = JSON.stringify(PayloadObj);
        const Payload = this.utils.stringToHex(jsonstr);

        const Timestamp = this.utils.getFormattedTimestamp();
        const ID = sha256(blockchain + From + To + Payload + Nonce + Timestamp);
        const Signature = "";

        try {
            await this.sendTransaction(ID, From, To, Timestamp, Type, Payload, Nonce, Signature, blockchain);
        } catch (error) {
            console.error('Error sending transaction:', error);
            throw error;
        }

        return ID;
    }
}

/**
 * LLMs.txt/AGENTS.md Metadata:
 * Circular Protocol - Standard APIs SDK
 * This file, 'ContractAPI.js', is part of the Circular Protocol JavaScript SDK
 * for Standard API/Blockchain interaction with the Circular Layer 1 Blockchain.
 * 
 * Module: ContractAPI
 * Purpose: Provides smart contract operations including testing contracts
 *          and making local contract calls.
 * 
 * Circular Protocol SDK - https://circular-protocol.gitbook.io/standard-apis
 * Circular Global Ledgers, Inc. - USA
 * ============================================================================
 */


/**
 * Smart contract operations for the Circular Protocol SDK.
 */
class ContractAPI {
    /**
     * Create a ContractAPI instance.
     * @param {Function} getNAGURL - Function to get current NAG URL.
     * @param {string} version - SDK version string.
     * @param {Utils} utils - Utils instance.
     */
    constructor(getNAGURL, version, utils) {
        this.getNAGURL = getNAGURL;
        this.version = version;
        this.utils = utils;
    }

    /**
     * Test the execution of a smart contract project.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} from - Developer's wallet address.
     * @param {string} project - Hyper Code Light Smart Contract Project.
     * @returns {Promise<Object>} Contract test result.
     */
    async testContract(blockchain, from, project) {
        const data = {
            "Blockchain": this.utils.hexFix(blockchain),
            "From": this.utils.hexFix(from),
            "Timestamp": this.utils.getFormattedTimestamp(),
            "Project": this.utils.stringToHex(project),
            "Version": this.version
        };

        try {
            const response = await fetch(this.getNAGURL() + 'Circular_TestContract_', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data)
            });

            if (!response.ok) {
                throw new Error('Network response was not ok');
            }

            return await response.json();
        } catch (error) {
            console.error('Error:', error);
            return null;
        }
    }

    /**
     * Make a local smart contract call.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} from - Caller wallet address.
     * @param {string} address - Smart contract address.
     * @param {string} request - Smart contract local endpoint.
     * @returns {Promise<Object>} Contract call result.
     */
    async callContract(blockchain, from, address, request) {
        const data = {
            "Blockchain": this.utils.hexFix(blockchain),
            "From": this.utils.hexFix(from),
            "Address": this.utils.hexFix(address),
            "Request": this.utils.stringToHex(request),
            "Timestamp": this.utils.getFormattedTimestamp(),
            "Version": this.version
        };

        try {
            const response = await fetch(this.getNAGURL() + 'Circular_CallContract_', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data)
            });

            if (!response.ok) {
                throw new Error('Network response was not ok');
            }

            return await response.json();
        } catch (error) {
            console.error('Error:', error);
            return null;
        }
    }
}

/**
 * LLMs.txt/AGENTS.md Metadata:
 * Circular Protocol - Standard APIs SDK
 * This file, 'Domain.js', is part of the Circular Protocol JavaScript SDK
 * for Standard API/Blockchain interaction with the Circular Layer 1 Blockchain.
 *
 * Module: BlockchainAPI/Domain
 * Purpose: Handles domain resolution operations.
 */


/**
 * Resolve a domain name to a wallet address.
 * @param {string} blockchain - Blockchain identifier.
 * @param {string} name - Domain name.
 * @returns {Promise<Object>} Domain resolution result.
 */
async function getDomain(blockchain, name) {
    const data = {
        "Blockchain": this.utils.hexFix(blockchain),
        "Domain": name,
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_ResolveDomain_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        return await response.json();
    } catch (error) {
        console.error('Error fetching domain:', error);
        return null;
    }
}

var Domain = /*#__PURE__*/Object.freeze({
    __proto__: null,
    getDomain: getDomain
});

/**
 * LLMs.txt/AGENTS.md Metadata:
 * Circular Protocol - Standard APIs SDK
 * This file, 'Asset.js', is part of the Circular Protocol JavaScript SDK
 * for Standard API/Blockchain interaction with the Circular Layer 1 Blockchain.
 *
 * Module: BlockchainAPI/Asset
 * Purpose: Handles asset operations.
 */


/**
 * Get list of all assets minted on a blockchain.
 * @param {string} blockchain - Blockchain identifier.
 * @returns {Promise<Object>} Asset list.
 */
async function getAssetList(blockchain) {
    const data = {
        "Blockchain": this.utils.hexFix(blockchain),
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_GetAssetList_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        return await response.json();
    } catch (error) {
        console.error('Error fetching asset list:', error);
        return null;
    }
}

/**
 * Get an asset descriptor.
 * @param {string} blockchain - Blockchain identifier.
 * @param {string} name - Asset name (e.g., 'CIRX').
 * @returns {Promise<Object>} Asset descriptor.
 */
async function getAsset(blockchain, name) {
    const data = {
        "Blockchain": this.utils.hexFix(blockchain),
        "AssetName": name,
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_GetAsset_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        return await response.json();
    } catch (error) {
        console.error('Error fetching asset:', error);
        return null;
    }
}

/**
 * Get supply information for an asset.
 * @param {string} blockchain - Blockchain identifier.
 * @param {string} name - Asset name.
 * @returns {Promise<Object>} Asset supply info.
 */
async function getAssetSupply(blockchain, name) {
    const data = {
        "Blockchain": this.utils.hexFix(blockchain),
        "AssetName": name,
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_GetAssetSupply_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        return await response.json();
    } catch (error) {
        console.error('Error fetching asset supply:', error);
        return null;
    }
}

var Asset = /*#__PURE__*/Object.freeze({
    __proto__: null,
    getAsset: getAsset,
    getAssetList: getAssetList,
    getAssetSupply: getAssetSupply
});

/**
 * LLMs.txt/AGENTS.md Metadata:
 * Circular Protocol - Standard APIs SDK
 * This file, 'Voucher.js', is part of the Circular Protocol JavaScript SDK
 * for Standard API/Blockchain interaction with the Circular Layer 1 Blockchain.
 *
 * Module: BlockchainAPI/Voucher
 * Purpose: Handles voucher operations.
 */


/**
 * Get a voucher by code.
 * @param {string} blockchain - Blockchain identifier.
 * @param {string} code - Voucher code.
 * @returns {Promise<Object>} Voucher information.
 */
async function getVoucher(blockchain, code) {
    code = String(code);
    if (code.startsWith('0x')) {
        code = code.slice(2);
    }

    const data = {
        "Blockchain": this.utils.hexFix(blockchain),
        "Code": code,
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_GetVoucher_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        return await response.json();
    } catch (error) {
        console.error('Error fetching voucher:', error);
        return null;
    }
}

var Voucher = /*#__PURE__*/Object.freeze({
    __proto__: null,
    getVoucher: getVoucher
});

/**
 * LLMs.txt/AGENTS.md Metadata:
 * Circular Protocol - Standard APIs SDK
 * This file, 'Block.js', is part of the Circular Protocol JavaScript SDK
 * for Standard API/Blockchain interaction with the Circular Layer 1 Blockchain.
 *
 * Module: BlockchainAPI/Block
 * Purpose: Handles block operations.
 */


/**
 * Get blocks in a specified range.
 * @param {string} blockchain - Blockchain identifier.
 * @param {number} start - Start block number.
 * @param {number} end - End block number (if 0, start is count from latest).
 * @returns {Promise<Object>} Block range.
 */
async function getBlockRange(blockchain, start, end) {
    const data = {
        "Blockchain": this.utils.hexFix(blockchain),
        "Start": String(start),
        "End": String(end),
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_GetBlockRange_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        console.log(JSON.stringify(response));
        return await response.json();
    } catch (error) {
        console.error('Error fetching block range:', error);
        return null;
    }
}

/**
 * Get a specific block.
 * @param {string} blockchain - Blockchain identifier.
 * @param {number} num - Block number.
 * @returns {Promise<Object>} Block data.
 */
async function getBlock(blockchain, num) {
    const data = {
        "Blockchain": this.utils.hexFix(blockchain),
        "BlockNumber": String(num),
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_GetBlock_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        return await response.json();
    } catch (error) {
        console.error('Error fetching block:', error);
        return null;
    }
}

/**
 * Get the blockchain block height.
 * @param {string} blockchain - Blockchain identifier.
 * @returns {Promise<Object>} Block count.
 */
async function getBlockCount(blockchain) {
    const data = {
        "Blockchain": this.utils.hexFix(blockchain),
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_GetBlockHeight_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        return await response.json();
    } catch (error) {
        console.error('Error fetching block count:', error);
        return null;
    }
}

var Block = /*#__PURE__*/Object.freeze({
    __proto__: null,
    getBlock: getBlock,
    getBlockCount: getBlockCount,
    getBlockRange: getBlockRange
});

/**
 * LLMs.txt/AGENTS.md Metadata:
 * Circular Protocol - Standard APIs SDK
 * This file, 'Analytics.js', is part of the Circular Protocol JavaScript SDK
 * for Standard API/Blockchain interaction with the Circular Layer 1 Blockchain.
 *
 * Module: BlockchainAPI/Analytics
 * Purpose: Handles analytics operations.
 */


/**
 * Get blockchain analytics.
 * @param {string} blockchain - Blockchain identifier.
 * @returns {Promise<Object>} Analytics data.
 */
async function getAnalytics(blockchain) {
    const data = {
        "Blockchain": this.utils.hexFix(blockchain),
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_GetAnalytics_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        return await response.json();
    } catch (error) {
        console.error('Error fetching analytics:', error);
        return null;
    }
}

/**
 * Get list of available blockchains.
 * @returns {Promise<Object>} Blockchain list.
 */
async function getBlockchains() {
    const data = {};

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_GetBlockchains_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        return await response.json();
    } catch (error) {
        console.error('Error fetching blockchains:', error);
        return null;
    }
}

var Analytics = /*#__PURE__*/Object.freeze({
    __proto__: null,
    getAnalytics: getAnalytics,
    getBlockchains: getBlockchains
});

/**
 * LLMs.txt/AGENTS.md Metadata:
 * Circular Protocol - Standard APIs SDK
 * This file, 'Transaction.js', is part of the Circular Protocol JavaScript SDK
 * for Standard API/Blockchain interaction with the Circular Layer 1 Blockchain.
 *
 * Module: BlockchainAPI/Transaction
 * Purpose: Handles transaction operations.
 */


/**
 * Get a pending transaction by ID.
 * @param {string} blockchain - Blockchain identifier.
 * @param {string} txID - Transaction ID.
 * @returns {Promise<Object>} Pending transaction.
 */
async function getPendingTransaction(blockchain, txID) {
    const data = {
        "Blockchain": this.utils.hexFix(blockchain),
        "ID": this.utils.hexFix(txID),
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_GetPendingTransaction_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        return await response.json();
    } catch (error) {
        console.error('Error fetching pending transaction:', error);
        return null;
    }
}

/**
 * Get a transaction by ID.
 * @param {string} blockchain - Blockchain identifier.
 * @param {string} txID - Transaction ID.
 * @param {number} start - Start block.
 * @param {number} end - End block (if 0, start is count from latest).
 * @returns {Promise<Object>} Transaction data.
 */
async function getTransactionbyID(blockchain, txID, start, end) {
    const data = {
        "Blockchain": this.utils.hexFix(blockchain),
        "ID": this.utils.hexFix(txID),
        "Start": String(start),
        "End": String(end),
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_GetTransactionbyID_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        return await response.json();
    } catch (error) {
        console.error('Error fetching transaction by ID:', error);
        return null;
    }
}

/**
 * Get transactions by broadcasting node.
 * @param {string} blockchain - Blockchain identifier.
 * @param {string} nodeID - Node ID.
 * @param {number} start - Start block.
 * @param {number} end - End block.
 * @returns {Promise<Object>} Transactions.
 */
async function getTransactionbyNode(blockchain, nodeID, start, end) {
    const data = {
        "Blockchain": this.utils.hexFix(blockchain),
        "NodeID": this.utils.hexFix(nodeID),
        "Start": String(start),
        "End": String(end),
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_GetTransactionbyNode_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        return await response.json();
    } catch (error) {
        console.error('Error fetching transaction by node:', error);
        return this.utils.handleError ? this.utils.handleError(error) : null;
    }
}

/**
 * Get transactions by address.
 * @param {string} blockchain - Blockchain identifier.
 * @param {string} address - Wallet address.
 * @param {number} start - Start block.
 * @param {number} end - End block.
 * @returns {Promise<Object>} Transactions.
 */
async function getTransactionbyAddress(blockchain, address, start, end) {
    const data = {
        "Blockchain": this.utils.hexFix(blockchain),
        "Address": this.utils.hexFix(address),
        "Start": String(start),
        "End": String(end),
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_GetTransactionbyAddress_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        return await response.json();
    } catch (error) {
        console.error('Error fetching transactions by address:', error);
        return this.utils.handleError ? this.utils.handleError(error) : null;
    }
}

/**
 * Get transactions by date range.
 * @param {string} blockchain - Blockchain identifier.
 * @param {string} address - Wallet address.
 * @param {string} startDate - Start date.
 * @param {string} endDate - End date.
 * @returns {Promise<Object>} Transactions.
 */
async function getTransactionbyDate(blockchain, address, startDate, endDate) {
    const data = {
        "Blockchain": this.utils.hexFix(blockchain),
        "Address": this.utils.hexFix(address),
        "StartDate": startDate,
        "EndDate": endDate,
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_GetTransactionbyDate_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        return await response.json();
    } catch (error) {
        console.error('Error fetching transactions by date:', error);
        return this.utils.handleError ? this.utils.handleError(error) : null;
    }
}

/**
 * Submit a transaction to the blockchain.
 * @param {string} id - Transaction ID.
 * @param {string} from - Sender address.
 * @param {string} to - Recipient address.
 * @param {string} timestamp - Formatted timestamp.
 * @param {string} type - Transaction type.
 * @param {string} payload - Transaction payload.
 * @param {string} nonce - Wallet nonce.
 * @param {string} signature - Transaction signature.
 * @param {string} blockchain - Blockchain identifier.
 * @returns {Promise<Object>} Transaction result.
 */
async function sendTransaction(id, from, to, timestamp, type, payload, nonce, signature, blockchain) {
    const data = {
        "ID": this.utils.hexFix(id),
        "From": this.utils.hexFix(from),
        "To": this.utils.hexFix(to),
        "Timestamp": timestamp,
        "Payload": String(this.utils.hexFix(payload)),
        "Nonce": String(nonce),
        "Signature": this.utils.hexFix(signature),
        "Blockchain": this.utils.hexFix(blockchain),
        "Type": type,
        "Version": this.version
    };

    try {
        const response = await fetch(this.getNAGURL() + 'Circular_AddTransaction_', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });

        const text = await response.text();

        try {
            return JSON.parse(text);
        } catch (e) {
            return { status: response.status, message: text };
        }
    } catch (error) {
        console.error('Error sending transaction:', error);
        this.utils.handleError(error);
        return { success: false, message: 'Server unreachable', error: error.toString() };
    }
}

/**
 * Poll for transaction outcome with timeout.
 * @param {string} blockchain - Blockchain identifier.
 * @param {string} txID - Transaction ID.
 * @param {number} timeoutSec - Timeout in seconds.
 * @param {number} intervalSec - Polling interval in seconds.
 * @returns {Promise<Object>} Transaction outcome.
 */
function getTransactionOutcome(blockchain, txID, timeoutSec, intervalSec) {
    return new Promise((resolve, reject) => {
        const startTime = Date.now();
        const interval = intervalSec * 1000;
        const timeout = timeoutSec * 1000;

        const checkTransaction = () => {
            const elapsedTime = Date.now() - startTime;
            console.log('Checking transaction...', { elapsedTime, timeout });

            if (elapsedTime > timeout) {
                console.log('Timeout exceeded');
                reject(new Error('Timeout exceeded'));
                return;
            }

            this.getTransactionbyID(blockchain, txID, 0, 10)
                .then(data => {
                    console.log('Data received:', data);
                    if (data.Result === 200 && data.Response !== 'Transaction Not Found' && data.Response.Status !== 'Pending') {
                        resolve(data.Response);
                    } else {
                        console.log('Transaction not yet confirmed or not found, polling again...');
                        setTimeout(checkTransaction, interval);
                    }
                })
                .catch(error => {
                    console.log('Error fetching transaction:', error);
                    reject(error);
                });
        };

        setTimeout(checkTransaction, interval);
    });
}

var Transaction = /*#__PURE__*/Object.freeze({
    __proto__: null,
    getPendingTransaction: getPendingTransaction,
    getTransactionOutcome: getTransactionOutcome,
    getTransactionbyAddress: getTransactionbyAddress,
    getTransactionbyDate: getTransactionbyDate,
    getTransactionbyID: getTransactionbyID,
    getTransactionbyNode: getTransactionbyNode,
    sendTransaction: sendTransaction
});

/**
 * LLMs.txt/AGENTS.md Metadata:
 * Circular Protocol - Standard APIs SDK
 * This file, 'BlockchainAPI.js', is part of the Circular Protocol JavaScript SDK
 * for Standard API/Blockchain interaction with the Circular Layer 1 Blockchain.
 * 
 * Module: BlockchainAPI
 * Purpose: Aggregates modular blockchain operations (Domain, Asset, Voucher,
 *          Block, Analytics, Transaction) into a single class.
 * 
 * Circular Protocol SDK - https://circular-protocol.gitbook.io/standard-apis
 * Circular Global Ledgers, Inc. - USA
 * ============================================================================
 */


/**
 * Blockchain query and transaction operations for the Circular Protocol SDK.
 */
class BlockchainAPI {
    /**
     * Create a BlockchainAPI instance.
     * @param {Function} getNAGURL - Function to get current NAG URL.
     * @param {string} version - SDK version string.
     * @param {Utils} utils - Utils instance.
     */
    constructor(getNAGURL, version, utils) {
        this.getNAGURL = getNAGURL;
        this.version = version;
        this.utils = utils;
    }
}

// Assign methods to prototype to maintain flat API structure
Object.assign(BlockchainAPI.prototype, Domain);
Object.assign(BlockchainAPI.prototype, Asset);
Object.assign(BlockchainAPI.prototype, Voucher);
Object.assign(BlockchainAPI.prototype, Block);
Object.assign(BlockchainAPI.prototype, Analytics);
Object.assign(BlockchainAPI.prototype, Transaction);

/**
 * LLMs.txt/AGENTS.md Metadata:
 * Circular Protocol - Standard APIs SDK
 * This file, 'index.js', is the main non-breaking FACADE for the Circular
 * Protocol JavaScript SDK for Standard API/Blockchain interaction with the
 * Circular Layer 1 Blockchain.
 * 
 * Purpose: Manages configuration state (NAG_URL, NAG_KEY) and delegates all
 *          public method calls to internal modular components (WalletAPI,
 *          ContractAPI, BlockchainAPI, CryptoService, Utils), ensuring
 *          backward compatibility for external consumers.
 * 
 * Version: 1.0.14
 * 
 * Circular Protocol SDK - https://circular-protocol.gitbook.io/standard-apis
 * Circular Global Ledgers, Inc. - USA
 * 
 * Originator: Gianluca De Novi, PhD
 * Contributors: Danny De Novi, redorc83
 * 
 * Creation: 7/12/2022
 * Update: 28/01/2025
 * ============================================================================
 */


// --- Configuration State (Retained in Facade) ---
let NAG_URL = 'https://nag.circularlabs.io/NAG.php?cep=';
let NAG_KEY = '';
const VERSION = '1.0.8';

// --- Configuration Getters (for dependency injection to modules) ---
const getNAGURL = () => NAG_URL;

// --- Initialize Internal Delegates ---
const utils = new Utils();
const crypto = new CryptoService(utils);
const blockchain = new BlockchainAPI(getNAGURL, VERSION, utils);
const contract = new ContractAPI(getNAGURL, VERSION, utils);
// WalletAPI needs sendTransaction reference, will be set after blockchain is ready
const wallet = new WalletAPI(getNAGURL, VERSION, utils,
    (id, from, to, timestamp, type, payload, nonce, signature, chain) =>
        blockchain.sendTransaction(id, from, to, timestamp, type, payload, nonce, signature, chain)
);

/**
 * Circular Protocol API - Non-Breaking Facade
 * 
 * All public methods delegate to internal modular implementations.
 * The interface remains identical to the original SDK for backward compatibility.
 */
let CircularProtocolAPI = {

    // ==================== CONFIGURATION (Retained in Facade) ====================

    /**
     * Set the Application NAG Key.
     * @param {string} nagKey - NAG API key.
     */
    setNAGKey: function (nagKey) {
        NAG_KEY = nagKey;
    },

    /**
     * Get the current NAG Key.
     * @returns {string} NAG API key.
     */
    getNAGKey: function () {
        return NAG_KEY;
    },

    /**
     * Set the Network Access Gateway (NAG) URL.
     * @param {string} nURL - NAG URL.
     */
    setNAGURL: function (nURL) {
        NAG_URL = nURL;
    },

    /**
     * Get the current NAG URL.
     * @returns {string} NAG URL.
     */
    getNAGURL: function () {
        return NAG_URL;
    },

    // ==================== UTILITY FUNCTIONS (Delegated) ====================

    /**
     * Remove '0x' prefix from hex strings.
     * @param {string} word - Hex string.
     * @returns {string} Cleaned hex string.
     */
    hexFix: function (word) {
        return utils.hexFix(word);
    },

    /**
     * Convert string to hexadecimal.
     * @param {string} str - String to convert.
     * @returns {string} Hex representation.
     */
    stringToHex: function (str) {
        return utils.stringToHex(str);
    },

    /**
     * Convert hexadecimal to string.
     * @param {string} hex - Hex string to convert.
     * @returns {string} Decoded string.
     */
    hexToString: function (hex) {
        return utils.hexToString(hex);
    },

    /**
     * Get formatted UTC timestamp: YYYY:MM:DD-hh:mm:ss.
     * @returns {string} Formatted timestamp.
     */
    getFormattedTimestamp: function () {
        return utils.getFormattedTimestamp();
    },

    // ==================== CRYPTOGRAPHIC FUNCTIONS (Delegated) ====================

    /**
     * Hash a string using SHA256.
     * @param {string} str - String to hash.
     * @returns {string} SHA256 hash.
     */
    hashString: function (str) {
        return crypto.hashString(str);
    },

    /**
     * Sign a message using secp256k1.
     * @param {string} message - Message to sign.
     * @param {string} privateKey - Private key (hex format).
     * @returns {string} DER-encoded signature.
     */
    signMessage: function (message, privateKey) {
        return crypto.signMessage(message, privateKey);
    },

    /**
     * Verify a message signature.
     * @param {string} publicKey - Public key (hex format).
     * @param {string} message - Original message.
     * @param {string} signature - Signature to verify.
     * @returns {boolean} True if valid.
     */
    verifySignature: function (publicKey, message, signature) {
        return crypto.verifySignature(publicKey, message, signature);
    },

    /**
     * Derive public key from private key.
     * @param {string} privateKey - Private key (hex format).
     * @returns {string} Public key (hex format).
     */
    getPublicKey: function (privateKey) {
        return crypto.getPublicKey(privateKey);
    },

    // ==================== WALLET FUNCTIONS (Delegated) ====================

    /**
     * Check if a wallet is registered.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} address - Wallet address.
     * @returns {Promise<Object>} Wallet status.
     */
    checkWallet: function (blockchain, address) {
        return wallet.checkWallet(blockchain, address);
    },

    /**
     * Get wallet information.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} address - Wallet address.
     * @returns {Promise<Object>} Wallet data.
     */
    getWallet: function (blockchain, address) {
        return wallet.getWallet(blockchain, address);
    },

    /**
     * Get latest transactions for a wallet.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} address - Wallet address.
     * @returns {Promise<Object>} Latest transactions.
     */
    getLatestTransactions: function (blockchain, address) {
        return wallet.getLatestTransactions(blockchain, address);
    },

    /**
     * Get wallet balance for an asset.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} address - Wallet address.
     * @param {string} asset - Asset name (e.g., 'CIRX').
     * @returns {Promise<Object>} Balance information.
     */
    getWalletBalance: function (blockchain, address, asset) {
        return wallet.getWalletBalance(blockchain, address, asset);
    },

    /**
     * Get wallet nonce.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} address - Wallet address.
     * @returns {Promise<Object>} Nonce value.
     */
    getWalletNonce: function (blockchain, address) {
        return wallet.getWalletNonce(blockchain, address);
    },

    /**
     * Register a wallet on a blockchain.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} publicKey - Wallet public key.
     * @returns {Promise<string>} Transaction ID.
     */
    registerWallet: function (blockchain, publicKey) {
        return wallet.registerWallet(blockchain, publicKey);
    },

    // ==================== CONTRACT FUNCTIONS (Delegated) ====================

    /**
     * Test smart contract execution.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} from - Developer wallet address.
     * @param {string} project - Smart contract project.
     * @returns {Promise<Object>} Test result.
     */
    testContract: function (blockchain, from, project) {
        return contract.testContract(blockchain, from, project);
    },

    /**
     * Make a local smart contract call.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} from - Caller wallet address.
     * @param {string} address - Contract address.
     * @param {string} request - Contract endpoint.
     * @returns {Promise<Object>} Call result.
     */
    callContract: function (blockchain, from, address, request) {
        return contract.callContract(blockchain, from, address, request);
    },

    // ==================== DOMAIN FUNCTIONS (Delegated) ====================

    /**
     * Resolve domain to wallet address.
     * @param {string} blockchain - Blockchain identifier.
     * @param {string} name - Domain name.
     * @returns {Promise<Object>} Resolution result.
     */
    getDomain: function (blockchain, name) {
        return blockchain.getDomain(blockchain, name);
    },

    // ==================== ASSET FUNCTIONS (Delegated) ====================

    /**
     * Get list of all assets on blockchain.
     * @param {string} chain - Blockchain identifier.
     * @returns {Promise<Object>} Asset list.
     */
    getAssetList: function (chain) {
        return blockchain.getAssetList(chain);
    },

    /**
     * Get asset descriptor.
     * @param {string} chain - Blockchain identifier.
     * @param {string} name - Asset name.
     * @returns {Promise<Object>} Asset descriptor.
     */
    getAsset: function (chain, name) {
        return blockchain.getAsset(chain, name);
    },

    /**
     * Get asset supply information.
     * @param {string} chain - Blockchain identifier.
     * @param {string} name - Asset name.
     * @returns {Promise<Object>} Supply info.
     */
    getAssetSupply: function (chain, name) {
        return blockchain.getAssetSupply(chain, name);
    },

    // ==================== VOUCHER FUNCTIONS (Delegated) ====================

    /**
     * Get voucher information.
     * @param {string} chain - Blockchain identifier.
     * @param {string} code - Voucher code.
     * @returns {Promise<Object>} Voucher data.
     */
    getVoucher: function (chain, code) {
        return blockchain.getVoucher(chain, code);
    },

    // ==================== BLOCK FUNCTIONS (Delegated) ====================

    /**
     * Get blocks in a range.
     * @param {string} chain - Blockchain identifier.
     * @param {number} start - Start block.
     * @param {number} end - End block.
     * @returns {Promise<Object>} Block range.
     */
    getBlockRange: function (chain, start, end) {
        return blockchain.getBlockRange(chain, start, end);
    },

    /**
     * Get a specific block.
     * @param {string} chain - Blockchain identifier.
     * @param {number} num - Block number.
     * @returns {Promise<Object>} Block data.
     */
    getBlock: function (chain, num) {
        return blockchain.getBlock(chain, num);
    },

    /**
     * Get blockchain block height.
     * @param {string} chain - Blockchain identifier.
     * @returns {Promise<Object>} Block count.
     */
    getBlockCount: function (chain) {
        return blockchain.getBlockCount(chain);
    },

    // ==================== ANALYTICS FUNCTIONS (Delegated) ====================

    /**
     * Get blockchain analytics.
     * @param {string} chain - Blockchain identifier.
     * @returns {Promise<Object>} Analytics data.
     */
    getAnalytics: function (chain) {
        return blockchain.getAnalytics(chain);
    },

    /**
     * Get list of available blockchains.
     * @returns {Promise<Object>} Blockchain list.
     */
    getBlockchains: function () {
        return blockchain.getBlockchains();
    },

    // ==================== TRANSACTION FUNCTIONS (Delegated) ====================

    /**
     * Get pending transaction by ID.
     * @param {string} chain - Blockchain identifier.
     * @param {string} txID - Transaction ID.
     * @returns {Promise<Object>} Pending transaction.
     */
    getPendingTransaction: function (chain, txID) {
        return blockchain.getPendingTransaction(chain, txID);
    },

    /**
     * Get transaction by ID.
     * @param {string} chain - Blockchain identifier.
     * @param {string} txID - Transaction ID.
     * @param {number} start - Start block.
     * @param {number} end - End block.
     * @returns {Promise<Object>} Transaction data.
     */
    getTransactionbyID: function (chain, txID, start, end) {
        return blockchain.getTransactionbyID(chain, txID, start, end);
    },

    /**
     * Get transactions by node.
     * @param {string} chain - Blockchain identifier.
     * @param {string} nodeID - Node ID.
     * @param {number} start - Start block.
     * @param {number} end - End block.
     * @returns {Promise<Object>} Transactions.
     */
    getTransactionbyNode: function (chain, nodeID, start, end) {
        return blockchain.getTransactionbyNode(chain, nodeID, start, end);
    },

    /**
     * Get transactions by address.
     * @param {string} chain - Blockchain identifier.
     * @param {string} address - Wallet address.
     * @param {number} start - Start block.
     * @param {number} end - End block.
     * @returns {Promise<Object>} Transactions.
     */
    getTransactionbyAddress: function (chain, address, start, end) {
        return blockchain.getTransactionbyAddress(chain, address, start, end);
    },

    /**
     * Get transactions by date range.
     * @param {string} chain - Blockchain identifier.
     * @param {string} address - Wallet address.
     * @param {string} startDate - Start date.
     * @param {string} endDate - End date.
     * @returns {Promise<Object>} Transactions.
     */
    getTransactionbyDate: function (chain, address, startDate, endDate) {
        return blockchain.getTransactionbyDate(chain, address, startDate, endDate);
    },

    /**
     * Submit a transaction.
     * @param {string} id - Transaction ID.
     * @param {string} from - Sender address.
     * @param {string} to - Recipient address.
     * @param {string} timestamp - Formatted timestamp.
     * @param {string} type - Transaction type.
     * @param {string} payload - Transaction payload.
     * @param {string} nonce - Wallet nonce.
     * @param {string} signature - Transaction signature.
     * @param {string} chain - Blockchain identifier.
     * @returns {Promise<Object>} Transaction result.
     */
    sendTransaction: function (id, from, to, timestamp, type, payload, nonce, signature, chain) {
        return blockchain.sendTransaction(id, from, to, timestamp, type, payload, nonce, signature, chain);
    },

    /**
     * Poll for transaction outcome.
     * @param {string} chain - Blockchain identifier.
     * @param {string} txID - Transaction ID.
     * @param {number} timeoutSec - Timeout in seconds.
     * @param {number} intervalSec - Poll interval in seconds.
     * @returns {Promise<Object>} Transaction outcome.
     */
    getTransactionOutcome: function (chain, txID, timeoutSec, intervalSec) {
        return blockchain.getTransactionOutcome(chain, txID, timeoutSec, intervalSec);
    }
};

module.exports = CircularProtocolAPI;
